In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

In [6]:
data_dev = data[0:1000].T
# after transposing, columns represent training sample number.
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [8]:
n

785

In [ ]:
def init_params():
    W1 = np.random.rand(120,784)
    b1 = np.random.rand(120,1)
    W2 = np.random.rand(120,784)
    b2 = np.random.rand(120,1)
    W3 = np.random.rand(120,784)
    b3 = np.random.rand(120,1)
    
    return W1,b1,W2,b2,W3,b3

def ReLU(Z):
    return np.maximum(0,Z)

def forward_prop(W1,b1,W2,b2,W3,b3,X):
    Z1 = np.dot(W1,X) + b1
    A1 = ReLU(Z1)
    Z2 = np.dot(W2,A1) + b2
    A2 = ReLU(Z2)
    Z3 = np.dot(W3,A2) + b3
    A3 = Softmax(Z3)