In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('train.csv')

In [19]:
df.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
y = df.label
X_full = df.drop(['label'],axis = 1,inplace=False)
X_full = X_full/255

X_dev = X_full.iloc[0:1000,:]
y_dev = y.iloc[0:1000]

X_train = X_full.iloc[1000:X_full.shape[0],:]
y_train = y.iloc[1000:y.shape[0]]

## Part 1: Neural Network Implementation

### ii) Activation Functions

In [39]:
def ReLU(x):
    if (x>0):
        return x
    else:
        return 0

In [40]:
def softmax(z):
    exp_z = np.exp(z)
    sum = exp_z.sum()
    softmax_z = np.round(exp_z/sum,3)
    return softmax_z

### iii) Forward Propagation

In [ ]:
def forward_propagation(W1,B1,W2,B2,W3,B3):
    Z1 = np.dot(W1,inp) + B1    
    A1 = ReLU(Z1)
    
    Z2 = np.dot(W2,inp) + B2    
    A2 = ReLU(Z2)
    
    Z3 = np.dot(W3,inp) + B3    
    A3 = softmax(Z3)
    
    return Z1,Z2,Z3,A1,A2,A3

In [ ]:
def one_hot(Y):